@echo off
echo Creating virtual environment...
python -m venv venv_naseri
echo Activating virtual environment...
call venv_naseri\Scripts\activate
echo Installing requirements...
pip install -r requirements.txt
echo Running migrations...
python manage.py migrate
echo Starting server...
python manage.py runserver
pause
