# Generated by Django 5.2.1 on 2025-05-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
