<template><section class="invoice-viewer" dir="rtl"><div class="invoice-toolbar"><div><strong>{{ title || 'مشاهده سند' }}</strong><small>نسخهٔ آمادهٔ چاپ A4 و اشتراک با QR</small></div><div class="invoice-actions"><button :disabled="!invoice || busy || !qrReady" class="invoice-button primary" @click="download">{{ busy ? 'در حال آماده‌سازی…' : 'دانلود PDF' }}</button><button :disabled="!invoice || busy || !qrReady" class="invoice-button" @click="print">چاپ A4</button><button v-if="closable" class="invoice-button close" aria-label="بستن فاکتور" @click="$emit('close')">×</button></div></div><p v-if="error" role="alert" class="invoice-feedback">{{ error }}</p><div v-if="loading" role="status" class="invoice-empty">در حال دریافت اطلاعات سند…</div><div v-else-if="!invoice" class="invoice-empty"><h2>سند در دسترس نیست</h2><p>{{ loadError || 'دریافت اطلاعات سند ممکن نشد. اتصال اینترنت را بررسی کنید.' }}</p><button class="invoice-button" @click="$emit('retry')">تلاش دوباره</button></div><div v-else ref="paper"><InvoiceDocument  :document="invoice" @qr-ready="qrReady = $event" /></div></section></template>
<script setup>
import { ref } from 'vue'
import InvoiceDocument from './InvoiceDocument.vue'
import { downloadInvoicePDF, printInvoice } from '@/utils/invoicePdf'
const props = defineProps({ invoice: Object, loading: Boolean, loadError: String, title: String, closable: Boolean }); defineEmits(['close', 'retry'])
const qrReady = ref(false), paper = ref(null), busy = ref(false), error = ref('')
const download = async () => { busy.value = true; error.value = ''; try { await downloadInvoicePDF(paper.value.firstElementChild, props.invoice.number) } catch { error.value = 'دانلود PDF ممکن نشد. از «چاپ A4» و گزینهٔ ذخیره به صورت PDF مرورگر استفاده کنید.' } finally { busy.value = false } }
const print = async () => { error.value = ''; try { await printInvoice(paper.value.firstElementChild) } catch { error.value = 'پنجرهٔ چاپ باز نشد. دسترسی چاپ مرورگر را بررسی کنید.' } }
</script>
<style>.invoice-viewer{max-width:980px;margin:auto;background:#eaf0ef;padding:24px;color:#1c3035}.invoice-toolbar{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:0 0 20px}.invoice-toolbar strong{font-size:16px}.invoice-toolbar small{display:block;color:#52646a;font-size:11px;margin-top:4px}.invoice-actions{display:flex;gap:8px;flex-wrap:wrap}.invoice-button{padding:10px 15px;border:1px solid #b7c8c8;border-radius:5px;background:white;color:#245a56;font-size:12px;cursor:pointer;line-height:1.5}.invoice-button.primary{background:#245f5a;border-color:#245f5a;color:white}.invoice-button:hover{filter:brightness(.95)}.invoice-button:focus-visible{outline:3px solid #9dc7c1;outline-offset:3px}.invoice-button:disabled{opacity:.5;cursor:wait}.invoice-button.close{font-size:20px;padding:5px 12px}.invoice-empty{padding:60px 20px;text-align:center;background:white}.invoice-empty p{margin:15px 0;color:#52646a}.invoice-feedback{padding:14px;background:#fff5ed;color:#803600;margin-bottom:15px;font-size:13px}.invoice-viewer .invoice-paper{box-shadow:0 6px 26px #183c3510}@media(max-width:600px){.invoice-viewer{padding:14px 10px}.invoice-toolbar{align-items:flex-start;flex-direction:column;gap:14px}.invoice-actions{width:100%}.invoice-button{padding:10px 12px}.invoice-actions .primary{flex:1}.invoice-viewer .invoice-paper{box-shadow:none}}</style>
