# Generated by Django 5.0.7 on 2025-08-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return_from_customer', 'Return from Customer'), ('return_to_supplier', 'Return to Supplier'), ('adjustment_add', 'Adjustment Add'), ('adjustment_subtract', 'Adjustment Subtract')], max_length=30, verbose_name='transaction type'),
        ),
    ]
