# Generated by Django 5.0.7 on 2025-08-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='invoice number'),
        ),
    ]
