# Generated by Django 5.0.7 on 2025-08-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tax_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], default='individual', max_length=20, verbose_name='customer type'),
        ),
        migrations.AddField(
            model_name='customer',
            name='business_category',
            field=models.CharField(blank=True, choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('contractor', 'Contractor'), ('other', 'Other')], max_length=20, verbose_name='business category'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms',
            field=models.IntegerField(default=30, verbose_name='payment terms (days)'),
        ),
    ]
