# Generated by Django 5.0.7 on 2025-08-20 08:40

from django.db import migrations, models


def populate_customer_codes(apps, schema_editor):
    """Populate customer codes for existing customers."""
    Customer = apps.get_model('sales', 'Customer')
    for i, customer in enumerate(Customer.objects.all(), 1):
        customer.customer_code = f'CUST{i:06d}'
        customer.save()


def reverse_populate_customer_codes(apps, schema_editor):
    """Reverse operation - clear customer codes."""
    Customer = apps.get_model('sales', 'Customer')
    Customer.objects.update(customer_code='')


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20250819_0923'),
    ]

    operations = [
        # Add customer_code field without unique constraint first
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='customer code'),
        ),
        # Populate customer codes
        migrations.RunPython(populate_customer_codes, reverse_populate_customer_codes),
        # Now add unique constraint
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='customer code'),
        ),
    ]
