# Generated by Django 5.0.7 on 2025-08-31 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorytransaction_transaction_type'),
        ('sales', '0005_add_customer_code_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.warehouse', verbose_name='warehouse'),
        ),
    ]
