# Generated by Django 5.0.7 on 2025-09-22 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('user_login', 'ورود کاربر'), ('user_logout', 'خروج کاربر'), ('user_created', 'ایجاد کاربر جدید'), ('user_updated', 'بروزرسانی کاربر'), ('user_deleted', 'حذف کاربر'), ('product_created', 'ایجاد محصول جدید'), ('product_updated', 'بروزرسانی محصول'), ('product_deleted', 'حذف محصول'), ('product_viewed', 'مشاهده محصول'), ('category_created', 'ایجاد دسته\u200cبندی جدید'), ('category_updated', 'بروزرسانی دسته\u200cبندی'), ('category_deleted', 'حذف دسته\u200cبندی'), ('customer_created', 'ایجاد مشتری جدید'), ('customer_updated', 'بروزرسانی اطلاعات مشتری'), ('customer_deleted', 'حذف مشتری'), ('sale_created', 'ایجاد فاکتور جدید'), ('sale_confirmed', 'تأیید فاکتور فروش'), ('sale_completed', 'تکمیل فاکتور فروش'), ('sale_cancelled', 'لغو فاکتور فروش'), ('sale_updated', 'بروزرسانی فاکتور'), ('receipt_generated', 'تولید رسید'), ('receipt_printed', 'چاپ رسید'), ('stock_adjustment', 'تعدیل موجودی'), ('stock_low_warning', 'هشدار موجودی کم'), ('inventory_transaction', 'تراکنش موجودی'), ('purchase_created', 'ایجاد سفارش خرید'), ('purchase_confirmed', 'تأیید سفارش خرید'), ('purchase_received', 'دریافت کالا'), ('purchase_cancelled', 'لغو سفارش خرید'), ('payment_received', 'دریافت پرداخت'), ('payment_made', 'انجام پرداخت'), ('payment_cancelled', 'لغو پرداخت'), ('backup_created', 'تهیه پشتیبان'), ('report_generated', 'تولید گزارش'), ('system_error', 'خطای سیستم'), ('data_export', 'صادرات داده\u200cها'), ('data_import', 'واردات داده\u200cها')], max_length=50)),
                ('title', models.CharField(help_text='عنوان فعالیت', max_length=255)),
                ('description', models.TextField(blank=True, help_text='توضیحات تفصیلی')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('critical', 'بحرانی')], default='medium', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='اطلاعات اضافی در فرمت JSON')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('requires_notification', models.BooleanField(default=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='کاربر انجام\u200cدهنده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فعالیت',
                'verbose_name_plural': 'فعالیت\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity_type', '-created_at'], name='audit_activ_activit_20c287_idx'), models.Index(fields=['user', '-created_at'], name='audit_activ_user_id_81ad2b_idx'), models.Index(fields=['priority', '-created_at'], name='audit_activ_priorit_e1d8e6_idx'), models.Index(fields=['is_read', 'requires_notification'], name='audit_activ_is_read_00f91c_idx')],
            },
        ),
    ]
